name: AutoSync iStore

on:
  schedule:
    - cron: '0 20 * * *'  # UTC时间20点(北京时间次日4点)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Execute sync script
      run: |
        chmod +x diy.sh
        ./diy.sh

    - name: Update repository
      run: |
        # 仅删除需要覆盖的旧文件
        if [ -d "_temp_sync" ]; then
          # 创建保留列表
          keep_files=(
            .git
            .github
            diy.sh
          )
          
          # 删除非保留文件
          find . -mindepth 1 -maxdepth 1 \
            $(printf -- '-not -name "%s" ' "${keep_files[@]}") \
            -exec rm -rf {} +
          
          # 移动新内容（保留.git等目录）
          shopt -s dotglob
          mv -f _temp_sync/* . 2>/dev/null || true
        fi

        # 提交变更
        git config --global user.name "iStore AutoSync"
        git config --global user.email "autosync@users.noreply.github.com"
        git add .
        git commit -m "AutoSync: $(date +'%Y%m%d-%H%M%S')" || echo "No changes"
        git push origin main

    - name: Final cleanup
      run: |
        rm -rf _temp_sync
