name: AutoSync iStore

on:
  schedule:
    - cron: '0 20 * * *'  # UTC时间20点(北京时间次日4点)
  workflow_dispatch:
    inputs:
      force:
        description: '强制同步'
        required: false
        default: 'false'
  push:
    paths:
      - '.github/workflows/sync.yml'
      - 'diy.sh'

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [main]
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup environment
      run: |
        git config --global user.name "iStore AutoSync"
        git config --global user.email "autosync@users.noreply.github.com"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Execute sync script
      run: |
        chmod +x diy.sh
        ./diy.sh

    - name: Commit changes
      env:
        COMMIT_MSG: "AutoSync: $(date +'%Y-%m-%d %H:%M:%S')"
      run: |
        if git status --porcelain | grep .; then
          git add .
          git commit -m "$COMMIT_MSG"
          git push origin main
        else
          echo "No changes to commit"
        fi

    - name: Clean workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 3
        keep_minimum_runs: 5
