name: Auto Sync Packages

on:
  schedule:
    - cron: '0 3 * * *'  # 每天UTC时间3点运行（北京时间11点）
  workflow_dispatch:     # 手动触发选项
    inputs:
      folders:
        description: '要同步的文件夹（空格分隔）'
        required: false
        default: 'luci-app-argon-config luci-theme-argon'

jobs:
  sync-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run Clone Script
        env:
          CLONE_FOLDERS: ${{ github.event.inputs.folders }}
        run: |
          # 动态修改克隆文件夹
          sed -i "s/^CLONE_FOLDERS=.*/CLONE_FOLDERS=\"$CLONE_FOLDERS\"/" clone.sh
          chmod +x clone.sh
          ./clone.sh

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
