name: AutoSync iStore

on:
  schedule:
    - cron: '0 20 * * *'  # UTC时间20点(北京时间次日4点)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Execute sync script
      run: |
        chmod +x diy.sh
        ./diy.sh

    - name: Clean and commit
      run: |
        # 移动文件（绝对路径操作）
        shopt -s dotglob
        [ -d "_temp_sync" ] && mv -f _temp_sync/* . 2>/dev/null || true
        
        # 提交变更
        git config --global user.name "iStore AutoSync"
        git config --global user.email "autosync@users.noreply.github.com"
        git add .
        git commit -m "AutoSync: $(date +'%Y%m%d-%H%M%S')" || echo "No changes"
        git push origin main

    - name: Final cleanup
      run: |
        rm -rf _temp_sync
